# Generated by Django 2.0.7 on 2018-08-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuser',
            name='slacktoken',
            field=models.CharField(default='xoxp-399005362672-399475669492-412590390742-bfbe15142f6e32961f716e554395dce9', max_length=200),
        ),
    ]
